blog/urls.py
from django.views.decorators.cache import cache_page
from django.urls import path
from blog.views import *
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('create/', MaterialsCreateView.as_view(), name='create'),
    path('', cache_page(60)(MaterialsListView.as_view()), name='list'),
    path('view/<int:pk>', MaterialsDetailView.as_view(), name='view'),
    path('edit/<int:pk>', MaterialsUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', MaterialsDeleteView.as_view(), name='delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("service.urls")),
    path('users/', include("users.urls")),
    path('blog/', include("blog.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path
from service.views import HomeView, ClientListView, MessageListView, ClientCreateView, ClientDeleteView, \
    ClientUpdateView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView, ActivateMessage
from service.apps import ServiceConfig
from django.views.decorators.cache import cache_page

app_name = ServiceConfig.name

urlpatterns = [
    path('', cache_page(60)(HomeView.as_view()), name='index'),
    path('clients/', ClientListView.as_view(), name='clients'),
    path('/clientcreate/', ClientCreateView.as_view(), name='clientcreate'),
    path('/clientupdate/<int:pk>/', ClientUpdateView.as_view(), name='clientupdate'),
    path('/clientdelete/<int:pk>/', ClientDeleteView.as_view(), name='clientdelete'),

    path('message/', MessageListView.as_view(), name='list'),
    path('messagedetail/<int:pk>/', MessageDetailView.as_view(), name='messagedetail'),
    path('messagecreate', MessageCreateView.as_view(), name='messagecreate'),
    path('messageupdate/<int:pk>/', MessageUpdateView.as_view(), name='messageupdate'),
    path('messagedelete/<int:pk>/', MessageDeleteView.as_view(), name='messagedelete'),
    path("/mailblock/<int:pk>/", ActivateMessage, name="block")


]

service/models.py
from django.db import models
# from django.forms import ModelForm
from django.utils import timezone

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(unique=True, verbose_name='почта')
    last_name = models.CharField(max_length=150, verbose_name='фамилия')
    first_name = models.CharField(max_length=150, verbose_name='имя')
    surname = models.CharField(max_length=150, verbose_name='отчество')
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)
    user = models.ForeignKey(User, related_name="clients", on_delete=models.CASCADE)

    def str(self) -> str:
        return f'{self.last_name} {self.first_name} {self.surname}, email: {self.email}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = "клиенты"
        ordering = ('first_name', 'last_name', 'surname')


class Message(models.Model):
    TITLE_CHOICES_PERIODICITY = [
        (1, 'Раз в день'),
        (2, 'Раз в неделю',),
        (3, 'Раз в месяц',),
    ]

    TITLE_CHOICES_STATUS = [
        (1, 'Создана'),
        (2, 'Запущена',),
        (3, 'Завершена',),
    ]
    theme = models.CharField(max_length=150, verbose_name='тема сообщения')
    body = models.TextField()
    mailing_time = models.TimeField(auto_now=False, auto_now_add=False, default=timezone.now, verbose_name='время  начала рассылки')
    periodicity = models.PositiveSmallIntegerField(verbose_name="периодичность", choices=TITLE_CHOICES_PERIODICITY,
                                                   default=1)
    status = models.PositiveSmallIntegerField(verbose_name='статус рассылки', choices=TITLE_CHOICES_STATUS, default=1)
    clients = models.ManyToManyField(Client, verbose_name='клиенты')
    user = models.ForeignKey(User, verbose_name='пользователь', on_delete=models.CASCADE, **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='состояние')
    def __str__(self):
        return f"{self.theme} {self.status}"

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = 'Сообщения'


class Log(models.Model):
    date_attempt = models.DateTimeField(verbose_name='Дата попытки')
    status = models.CharField(max_length=150, verbose_name='Статус попытки')
    answer = models.TextField(**NULLABLE, verbose_name='ответ сервера')
    mailing = models.ForeignKey(Message, **NULLABLE, on_delete=models.CASCADE)
    user = models.ForeignKey(Client, verbose_name='пользователь', on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.status} {self.date_attempt}"

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}

class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    comment = models.TextField(verbose_name='коментарий', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

service/forms.py
from django import forms

from service.models import Client, Message

class ClientForm(forms.ModelForm):

    class Meta:
        model = Client
        fields = ('first_name', 'last_name', 'surname', 'email', 'comment')
        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Имя клиента',
                }),

            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Фамилия клиента',
                }),

            'surname': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Отчество клиента',
                }),

            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Электронная почта клиента',
                }),

            'comment': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Ваш комментарий',
                'rows': 2,
                }),
        }


class MessageForm(forms.ModelForm):

    class Meta:
        model = Message
        fields = ('theme', 'body', 'mailing_time', 'periodicity', 'status', 'clients')

        widgets = {
            'theme': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Тема сообщения',
                }),

            'body': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст сообщения',
                'rows': 2,
                }),
            'mailing_time': forms.TimeInput(attrs={
                'type': 'time',
                'class': 'form-control',
            }),
        }

service/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, UpdateView, CreateView, DeleteView, DetailView

from service.forms import ClientForm, MessageForm
from service.models import *


class HomeView(TemplateView):
    template_name = 'service/index.html'


class ClientListView(LoginRequiredMixin, ListView):
    model = Client

    def get_queryset(self, *args, **kwargs):
        queryset = Client.objects.filter(user=self.request.user)
        return queryset


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    permission_required = 'service.change_message'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_managers"] = self.request.user.groups.filter(name='managers').exists()
        return context

    def get_queryset(self, *args, **kwargs):
        queryset = Message.objects.filter(user=self.request.user)
        if self.request.user.groups.filter(name='managers').exists():
            queryset = Message.objects.all()
        return queryset

class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("service:clients")


    def form_valid(self, form):
        client = form.save(commit=False)
        client.user = self.request.user
        client.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("service:clients")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy("service:clients")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message
    template_name = 'message/message_detail.html'

    # def get_context_data(self, **kwargs):
    #     context_data = super().get_context_data(**kwargs)
    #     if settings.CACHE_ENABLED:
    #         key = f'log_list_{self.object.pk}'
    #         log_list = cache.get(key)
    #         if log_list is None:
    #             log_list = self.object.log_set.all()
    #             cache.set(key, log_list)
    #     else:
    #         log_list = self.object.log_set.all()
    #     context_data['logs'] = log_list
    #
    #     return context_data


# def contact(request):
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         email = request.POST.get('email')
#         message = request.POST.get('message')
#         print(f'{name} {email} {message}')
#     context = {
#         'title': "Контакты"
#     }
#     return render(request, 'mailing/contact.html', context)


# def main(request):
#     clients = len(Client.objects.all().distinct('email'))
#     article = Article.objects.filter(is_published=True).order_by('?')
#     mailing = len(Mailing.objects.all())
#     mailing_active = len(Mailing.objects.filter(status=2))
#     context = {
#         'title': "Главная",
#         'article': article[:3],
#         'mailing': mailing,
#         'mailing_active': mailing_active,
#         'clients': clients
#     }
#     return render(request, 'mailing/main.html', context)


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    permission_required = 'message.add_message'
    success_url = reverse_lazy('service:list')

    # def form_valid(self, form):
    #     tz = pytz.timezone('Europe/Moscow')
    #     clients = [client.email for client in Client.objects.filter(user=self.request.user)]
    #     new_mailing = form.save()
    #
    #     if new_mailing.mailing_time <= datetime.now(tz):
    #         mail_subject = new_mailing.massage.body if new_mailing.massage is not None else 'Рассылка'
    #         message = new_mailing.massage.theme if new_mailing.massage is not None else 'Вам назначена рассылка'
    #         try:
    #             send_mail(mail_subject, message, settings.EMAIL_HOST_USER, clients)
    #             log = Log.objects.create(date_attempt=datetime.now(tz), status='Успешно', answer='200', mailing=new_mailing)
    #             log.save()
    #         except smtplib.SMTPDataError as err:
    #             log = Log.objects.create(date_attempt=datetime.now(tz), status='Ошибка', answer=err, mailing=new_mailing)
    #             log.save()
    #             #raise err
    #         except smtplib.SMTPException as err:
    #             log = Log.objects.create(date_attempt=datetime.now(tz), status='Ошибка', answer=err, mailing=new_mailing)
    #             log.save()
    #             #raise err
    #         except Exception as err:
    #             log = Log.objects.create(date_attempt=datetime.now(tz), status='Ошибка', answer=err, mailing=new_mailing)
    #             log.save()
    #             #raise err
    #         new_mailing.status = 3
    #         if new_mailing.user is None:
    #             new_mailing.user = self.request.user
    #         new_mailing.save()
    #
    #     return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    permission_required = 'message.change_message'
    success_url = reverse_lazy('service:list')


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    permission_required = 'message.delete_message'
    success_url = reverse_lazy('service:list')


@permission_required('service.change_message')
def ActivateMessage(request, pk):
    message = Message.objects.get(pk=pk)
    message.is_active = False if message.is_active else True
    message.save()
    return redirect('service:list')

service/templates/service/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Главная</a>
        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'service:clients' %}">Менеджер клиентов</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'service:list' %}">Менеджер рассылок</a>
        {% if perms.users.change_user %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:list' %}">Пользователи</a>
        {% endif %}
        <a class="p-2 btn btn-outline-primary" href="https://2ip.ru/">Нажми сюда</a>
        {% endif %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Блог</a>

        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
        <a class="p-2 btn btn-outline-primary" href="#">Профиль</a>
        {% else %}

        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">

        {% block content %}
        {% endblock %}

    </div>
    <!--    <div>-->
    <!--        {% for object in category_list %}-->
    <!--        {% include 'catalog/includes/inc_product_card.html' %} ТУТ СОЗДАМ КАРТОЧКУ СВОЮ НОВУЮ ПО КАТЕГОРНИЯМ-->
    <!--        {% endfor %}-->
    <!--    </div>-->

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>


        </div>
    </footer>
</div>
<script language="javascript">

// ENTER TEXT BELOW. CAN *NOT* INCLUDE NORMAL HTML CODE.
var text='SkyPro';

var delay=40; // SPEED OF TRAIL
var Xoff=0; // PIXEL COUNT FROM THE LEFT OF THE CURSOR (- VALUES GO TO LEFT)
var Yoff=-30; // PIXEL COUNT FROM THE TOP OF THE CURSOR (- VALUES GO UP)
var txtw=14; // AMOUNT OF PIXEL SPACE EACH CHARACTER OCCUPIES
var beghtml='<font color="blue"><b>'; // OPTIONAL HTML CODE THAT EFFECTS WHOLE TEXT STRING SUCH AS FONT COLOR, SIZE, ETC.
var endhtml='</b></font>'; // END HTML CODE. MOSTLY USED IF ABOVE SETTING IS USED.

//********** NO NEED TO EDIT BELOW HERE **********\\

ns4 = (navigator.appName.indexOf("Netscape")>=0 && document.layers)? true : false;
ie4 = (document.all && !document.getElementById)? true : false;
ie5 = (document.all && document.getElementById)? true : false;
ns6 = (document.getElementById && navigator.appName.indexOf("Netscape")>=0 )? true: false;
var txtA=new Array();
text=text.split('');
var x1=0;
var y1=-1000;
var t='';

for(i=1;i<=text.length;i++){
t+=(ns4)? '<layer name="txt'+i+'" top="-100" left="0" width="'+txtw+'" height="1">' : '<div id="txt'+i+'" style="position:absolute; top:-100px; left:0px; height:1px; width:'+txtw+'; visibility:visible;">';
t+=beghtml+text[i-1]+endhtml;
t+=(ns4)? '</layer>' : '</div>';
}
document.write(t);

function moveid(id,x,y){
if(ns4)id.moveTo(x,y);
else{
id.style.left=x+'px';
id.style.top=y+'px';
}}

function animate(evt){
x1=Xoff+((ie4||ie5)?event.clientX+document.body.scrollLeft:evt.pageX);
y1=Yoff+((ie4||ie5)?event.clientY+document.body.scrollTop:evt.pageY);
}

function getidleft(id){
if(ns4)return id.left;
else return parseInt(id.style.left);
}

function getidtop(id){
if(ns4)return id.top;
else return parseInt(id.style.top);
}

function getwindowwidth(){
if(ie4||ie5)return document.body.clientWidth+document.body.scrollLeft;
else return window.innerWidth+pageXOffset;
}

function movetxts(){
for(i=text.length;i>1;i=i-1){
if(getidleft(txtA[i-1])+txtw*2>=getwindowwidth()){
moveid(txtA[i-1],0,-1000);
moveid(txtA[i],0,-1000);
}else moveid(txtA[i], getidleft(txtA[i-1])+txtw, getidtop(txtA[i-1]));
}
moveid(txtA[1],x1,y1);
}

window.onload=function(){
for(i=1;i<=text.length;i++)txtA[i]=(ns4)?document.layers['txt'+i]:(ie4)?document.all['txt'+i]:document.getElementById('txt'+i);
if(ns4)document.captureEvents(Event.MOUSEMOVE);
document.onmousemove=animate;
setInterval('movetxts()',delay);
}
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>
</html>

service/templates/service/base1.html
{% load static %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Album example · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">



    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">


</head>

<body>

    <header>
        <div class="collapse bg-dark" id="navbarHeader">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-md-7 py-4">
                        <h4 class="text-white">About</h4>
                        <p class="text-muted">Add some information about the album below, the author, or any other
                            background context. Make it a few sentences long so folks can pick up some informative
                            tidbits. Then, link them off to some social networking sites or contact information.</p>
                    </div>
                    <div class="col-sm-4 offset-md-1 py-4">
                        <h4 class="text-white">Contact</h4>
                        <ul class="list-unstyled">
                            {% if user.is_authenticated %}
                                <li><a href="#" class="text-white">Главная</a></li>
                                <li><a href="#" class="text-white">Менеджер клиентов</a></li>
                                <li><a href="#" class="text-white">Менеджер рассылок</a></li>
                                <li><a href="" class="text-white">Отчёт о рассылках </a></li>
                                <li><a href="#" class="text-white">Выйти</a></li>
                            {% else %}
                            <li><a href="#" class="text-white">Войти</a></li>
                            <li><a href="#" class="text-white">Регистрация</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar navbar-dark bg-dark shadow-sm">
            <div class="container">
                <a href="#" class="navbar-brand d-flex align-items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                        stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                        viewBox="0 0 24 24">
                        <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" />
                        <circle cx="12" cy="13" r="4" />
                    </svg>
                    <strong>Album</strong>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </header>

    <main>
        {% block content%}
        {% endblock %}
    </main>

    <footer class="text-muted py-5">
        <div class="container">
            <p class="float-end mb-1">
                <a href="#">Back to top</a>
            </p>
            <p class="mb-1">Album example is © Bootstrap, but please download and customize it for yourself!</p>
            <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                    href="/docs/5.0/getting-started/introduction/">getting started guide</a>.</p>
        </div>
    </footer>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>


</body>

</html>

service/templates/service/client_confirm_delete.html
{% extends 'service/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить клиента "{{object.first_name}}"?</p>
                        <button type="submit" class="btn-danger">Подтвердить</button>
                        <a href="{% url 'service:clients' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

service/templates/service/client_form.html
{% extends 'service/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Клиент
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

service/templates/service/client_list.html
{% extends 'service/base.html' %}

{% block content %}


<section class="py-5 text-center container">
    <h1 class="fw-light">Клиенты</h1>
</section>


<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col-12 mb-6">
            <a class="btn btn-outline-primary" href="{% url 'service:clientcreate' %}">Добавить Клиента</a>
        </div>
        {% for object in object_list %}
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center button">
                        <p class="card-text">{{object|title}}</p>
                    </div>
                    <div class="btn-group">
                        <a href="#" type="button"
                            class="btn btn-sm btn-outline-secondary">update</a>
                        <a href="{% url 'service:clientdelete'  object.pk %}" type="button"
                            class="btn btn-sm btn-outline-secondary">Delete</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

service/templates/service/index.html
{% extends 'service/base.html' %}
{% block content %}
<div class="col-12 mb-5" >
    <a class="btn-btn-outline-primary" href="#">Добавить рассылку</a>
</div>


<!--    <div>-->
<!--        {% for object in category_list %}-->
<!--        {% include 'catalog/includes/inc_product_card.html' %} ТУТ СОЗДАМ КАРТОЧКУ СВОЮ НОВУЮ ПО КАТЕГОРНИЯМ-->
<!--        {% endfor %}-->
<!--    </div>-->

{% endblock %}

service/templates/service/message_confirm_delete.html
{% extends 'service/base.html'%}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'mailing:list'%}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

service/templates/service/message_detail.html
{% extends 'service/base.html'%}
{% block content %}

<div class="col-md-6">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">{{ object.mailing_time }}</p>
            <p class="card-text">{{ object.get_periodicity_display }}</p>
            <p class="card-text">
                {% if object.status == 3 %}
                    <span class="text-muted">{{ object.get_status_display }}</span>
                {% else %}
                    {{ object.get_status_display }}
                {% endif %}
            </p>
        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <div class="card-title">
                Отчет по отправке
            </div>
        </div>
        <div class="card-body">
            {% for log in logs %}
            <p class="card-text">{{ log.date_attempt }} {{ log.status }} {{ log.answer }}</p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

service/templates/service/message_form.html
{% extends 'service/base.html'%}
{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Добавление рассылки
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}